# Generated by Django 2.1.2 on 2018-10-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('contribution_type', models.CharField(max_length=255, verbose_name='Contribution Type')),
            ],
            options={
                'verbose_name': 'Contribution Type',
                'verbose_name_plural': 'Contribution Types',
            },
        ),
    ]
