# Generated by Django 2.1.2 on 2018-10-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0003_auto_20181025_1400'),
        ('accounts', '0003_auto_20181026_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ministry',
            field=models.ManyToManyField(blank=True, null=True, to='ministry.Ministry'),
        ),
    ]
