from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

'''
	This is the income App.
	In this app, all records of
	income generated by the church 
	or income generated by the church 
	for the church are recorded right here.
'''

class Income(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
	updated_on = models.DateTimeField(_('Updated On'), auto_now=True)
	created_on = models.DateTimeField(_('Created On'), auto_now_add=True)
	receipt_no = models.CharField(_('Receipt Number'), max_length=255, blank=True, null=True)
	income_date = models.DateField(_('Date'), blank=False, null=False)
	income_amount = models.IntegerField(_('Amount in Ksh.'), blank=False, null=False)
	income_description = models.TextField(_('Income Description'), blank=False, null=False)

	class Meta:
		verbose_name = "Income"
		verbose_name_plural = "Incomes"

	def __str__(self):
		return self.receipt_no