# Generated by Django 2.1.2 on 2018-10-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('receipt_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Receipt Number')),
                ('income_date', models.DateField(verbose_name='Date')),
                ('income_amount', models.IntegerField(verbose_name='Amount in Ksh.')),
                ('income_description', models.TextField(verbose_name='Income Description')),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Incomes',
            },
        ),
    ]
