# Generated by Django 2.1.2 on 2018-10-26 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181026_1230'),
        ('contribution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='member',
        ),
        migrations.AddField(
            model_name='contribution',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Member'),
        ),
    ]
