# Generated by Django 2.1.2 on 2018-10-25 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchAttendance', '0002_churchattendance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchattendance',
            name='user',
            field=models.ForeignKey(default=1, on_delete='Created By', to=settings.AUTH_USER_MODEL),
        ),
    ]
